# Generated by Django 2.2.6 on 2020-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='telephone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
