# Generated by Django 2.2.6 on 2020-02-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_bloguser_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'verbose_name': 'blog user', 'verbose_name_plural': 'blog users'},
        ),
        migrations.AddField(
            model_name='bloguser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
