# Generated by Django 2.2.6 on 2020-02-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200215_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
