# Generated by Django 2.2.6 on 2020-02-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_bloguser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='username',
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'telephone',
                'verbose_name_plural': 'telephones',
            },
        ),
    ]
