# Generated by Django 2.2.6 on 2020-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200215_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='email',
            field=models.CharField(default='aman@aman.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additional',
            name='name',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additional',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
