# Generated by Django 2.2.6 on 2020-02-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200219_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional',
            options={'verbose_name': 'additional info', 'verbose_name_plural': 'additional infos'},
        ),
    ]
