# Generated by Django 2.2.6 on 2020-02-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('apt', 'apartment'), ('hos', 'house'), ('peh', 'penthouse'), ('con', 'condo'), ('stu', 'studio')], default='hos', max_length=3)),
                ('status', models.CharField(choices=[('opn', 'open'), ('rem', 'removed'), ('pen', 'pending'), ('del', 'deleted'), ('clo', 'closed'), ('fro', 'frozen')], default='pen', max_length=3)),
                ('category', models.CharField(choices=[('sel', 'sell'), ('buy', 'buy'), ('cha', 'change'), ('ren', 'rent')], default='sel', max_length=3)),
                ('room', models.CharField(choices=[('1be', 'one bedroom'), ('2be', 'two bedrooms'), ('3be', 'three bedrooms'), ('4be', 'four bedrooms'), ('mor', 'more than 4 bedrooms')], default='2be', max_length=3)),
                ('age', models.CharField(choices=[('new', 'new'), ('05y', 'less than 5 years'), ('10y', 'less than 10 years'), ('10m', 'more than 10 years')], default='05y', max_length=3)),
                ('currency', models.CharField(choices=[('usd', 'dollars'), ('eur', 'euro'), ('rub', 'rubles'), ('man', 'manat'), ('ytl', 'lira')], default='usd', max_length=3)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Location')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
