# Generated by Django 2.2.6 on 2020-02-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
            preserve_default=False,
        ),
    ]
