# Generated by Django 2.2.6 on 2020-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='aman', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.CharField(choices=[('new', 'new'), ('less than 5 years', 'less than 5 years'), ('less than 10 years', 'less than 10 years'), ('more than 10 years', 'more than 10 years'), ('more than 20 years', 'more than 20 years')], default='less than 5 years', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('sell', 'sell'), ('buy', 'buy'), ('change', 'change'), ('rent', 'rent')], default='sell', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('penthouse', 'penthouse'), ('condo', 'condo'), ('studio', 'studio'), ('office', 'office'), ('store', 'store')], default='house', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.CharField(choices=[('one bedroom', 'one bedroom'), ('two bedrooms', 'two bedrooms'), ('three bedrooms', 'three bedrooms'), ('four bedrooms', 'four bedrooms'), ('more than 4 bedrooms', 'more than 4 bedrooms')], default='two bedrooms', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('removed', 'removed'), ('pending', 'pending'), ('deleted', 'deleted'), ('closed', 'closed'), ('frozen', 'frozen')], default='pending', max_length=25),
        ),
    ]
