# Generated by Django 2.2.6 on 2020-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200216_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footers',
            },
        ),
    ]
