# Generated by Django 2.2.6 on 2020-02-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
            preserve_default=False,
        ),
    ]
